# Generated by Django 3.1.3 on 2020-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterincident',
            name='incident_location',
            field=models.TextField(),
        ),
    ]
